### ISSUE TITLE
ToDo's

### ISSUE THREAD

**Issue by MariusVanDerWijden** [MariusVanDerWijden/tx-fuzz#36]
Things that I would like to do:

- [x] Refactor livefuzzer
- [x] Add Config struct
- [x] Provide easy way to integrate corpus
- [ ] Provide corpus / corpus generation
- [ ] Refactor helper functions, remove code from cmd/
- [ ] Refactor tx-fuzz package

**Comment by MariusVanDerWijden** [comment]
https://github.com/MariusVanDerWijden/tx-fuzz/pull/37 addresses issues 1 and 2

**Comment by MariusVanDerWijden** [comment]
I refactored the code base a lot, closing this for now
